// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvY8JiRvw3Q3yksBdWnm9gZirOhbhc7Y',
    appId: '1:100588736987:web:29066f25c8f3d8773fd7fe',
    messagingSenderId: '100588736987',
    projectId: 'student-sahara-program-37aa0',
    authDomain: 'student-sahara-program-37aa0.firebaseapp.com',
    storageBucket: 'student-sahara-program-37aa0.firebasestorage.app',
    measurementId: 'G-94SEJ473N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszyB5htE1WUNxsP2zBJdSlFZH_opNIvY',
    appId: '1:100588736987:android:e2181e62225345b43fd7fe',
    messagingSenderId: '100588736987',
    projectId: 'student-sahara-program-37aa0',
    storageBucket: 'student-sahara-program-37aa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZC4zBTqKB4tae0fVox2U-pR-abWfzbQ',
    appId: '1:100588736987:ios:cf3140f5d97fa8d13fd7fe',
    messagingSenderId: '100588736987',
    projectId: 'student-sahara-program-37aa0',
    storageBucket: 'student-sahara-program-37aa0.firebasestorage.app',
    iosBundleId: 'com.example.studentSaharaProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVZC4zBTqKB4tae0fVox2U-pR-abWfzbQ',
    appId: '1:100588736987:ios:cf3140f5d97fa8d13fd7fe',
    messagingSenderId: '100588736987',
    projectId: 'student-sahara-program-37aa0',
    storageBucket: 'student-sahara-program-37aa0.firebasestorage.app',
    iosBundleId: 'com.example.studentSaharaProgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuvY8JiRvw3Q3yksBdWnm9gZirOhbhc7Y',
    appId: '1:100588736987:web:1a1ee9a503036ee53fd7fe',
    messagingSenderId: '100588736987',
    projectId: 'student-sahara-program-37aa0',
    authDomain: 'student-sahara-program-37aa0.firebaseapp.com',
    storageBucket: 'student-sahara-program-37aa0.firebasestorage.app',
    measurementId: 'G-3DRXENS9S6',
  );
}
